name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  pull-request:
    name: test, report, and analyse
    uses: ./.github/workflows/build-test-analyse.yml
    secrets: inherit

  # job can be expanded to handle seperate pr actions such as close/merge/conflict
